version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5001:8080"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_MODE: dockercompose
    ports:
      - "5000:8080"